### ISSUE TITLE
Postgres insert failing 

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin-box#6]
Bridge server is failing with database insert every ~5 seconds when ran from the `origin-box` docker `scripts/start.sh` with the following output: 

```
origin-container | [2018-06-17 04:08:28,439: INFO/Beat] Scheduler: Sending due task util.tasks.event_listener() (util.tasks.event_listener)
origin-container | [2018-06-17 04:08:28,442: DEBUG/Beat] util.tasks.event_listener sent. id->81ecc87d-02c2-460a-8823-18d53c644eda
origin-container | [2018-06-17 04:08:28,443: DEBUG/Beat] beat: Waking up in 9.99 seconds.
origin-container | [2018-06-17 04:08:28,443: INFO/MainProcess] Received task: util.tasks.event_listener[81ecc87d-02c2-460a-8823-18d53c644eda]
origin-container | [2018-06-17 04:08:28,444: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x7f2ff6925730> (args:('util.tasks.event_listener', '81ecc87d-02c2-460a-8823-18d53c644eda', {'lang': 'py', 'task': 'util.tasks.event_listener', 'id': '81ecc87d-02c2-460a-8823-18d53c644eda', 'eta': None, 'expires': None, 'group': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '81ecc87d-02c2-460a-8823-18d53c644eda', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen157@0e700dbaafca', 'reply_to': 'e679f3e8-395b-3dc8-84c9-b354dd7b5344', 'correlation_id': '81ecc87d-02c2-460a-8823-18d53c644eda', 'delivery_info': {'exchange': '', 'routing_key': 'celery', 'priority': 0, 'redelivered': None}}, b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]', 'application/json', 'utf-8') kwargs:{})
origin-container | [2018-06-17 04:08:28,447: DEBUG/MainProcess] Task accepted: util.tasks.event_listener[81ecc87d-02c2-460a-8823-18d53c644eda] pid:156
origin-container | [2018-06-17 04:08:28,452: DEBUG/ForkPoolWorker-2] Resetting dropped connection: 127.0.0.1
origin-container | [2018-06-17 04:08:28,455: DEBUG/ForkPoolWorker-2] http://127.0.0.1:8545 "POST / HTTP/1.1" 200 None
origin-container | [2018-06-17 04:08:28,476: DEBUG/ForkPoolWorker-2] http://127.0.0.1:8545 "POST / HTTP/1.1" 200 None
origin-container | [2018-06-17 04:08:28,518: DEBUG/ForkPoolWorker-2] http://127.0.0.1:8545 "POST / HTTP/1.1" 200 None
origin-container | [2018-06-17 04:08:28,555: DEBUG/ForkPoolWorker-2] http://127.0.0.1:8545 "POST / HTTP/1.1" 200 None
origin-container | 2018-06-17 04:08:28 UTC [192-169] docker@bridge-server ERROR:  insert or update on table "purchase" violates foreign key constraint "purchase_listing_address_fkey"
origin-container | 2018-06-17 04:08:28 UTC [192-170] docker@bridge-server DETAIL:  Key (listing_address)=(0x4E205e04A1A8f230702fe51f3AfdCC38aafB0f3C) is not present in table "listing".
origin-container | 2018-06-17 04:08:28 UTC [192-171] docker@bridge-server STATEMENT:  INSERT INTO purchase (contract_address, buyer_address, listing_address, stage, created_at, buyer_timeout) VALUES ('0xCa163A64f8c3d8A6c15A46f95DA492476Ef3E613', '0xC5fdf4076b8F3A5357c5E395ab970B5B54098Fef', '0x4E205e04A1A8f230702fe51f3AfdCC38aafB0f3C', 1, '2018-06-17T03:59:00'::timestamp, '1970-01-01T00:00:00'::timestamp)
origin-container | [2018-06-17 04:08:28,577: ERROR/ForkPoolWorker-2] Task util.tasks.event_listener[81ecc87d-02c2-460a-8823-18d53c644eda] raised unexpected: IntegrityError('(psycopg2.IntegrityError) insert or update on table "purchase" violates foreign key constraint "purchase_listing_address_fkey"\nDETAIL:  Key (listing_address)=(0x4E205e04A1A8f230702fe51f3AfdCC38aafB0f3C) is not present in table "listing".\n',)
origin-container | Traceback (most recent call last):
origin-container |   File "/opt/bridge-server/bridge-server-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
origin-container |     context)
origin-container |   File "/opt/bridge-server/bridge-server-venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
origin-container |     cursor.execute(statement, parameters)
origin-container | psycopg2.IntegrityError: insert or update on table "purchase" violates foreign key constraint "purchase_listing_address_fkey"
origin-container | DETAIL:  Key (listing_address)=(0x4E205e04A1A8f230702fe51f3AfdCC38aafB0f3C) is not present in table "listing".
origin-container | The above exception was the direct cause of the following exception:
origin-container | Traceback (most recent call last):
origin-container |   File "/opt/bridge-server/bridge-server-venv/lib/python3.6/site-packages/celery/app/trace.py", line 374, in trace_task
origin-container |     R = retval = fun(*args, **kwargs)
origin-container |   File "/opt/bridge-server/source/util/tasks.py", line 33, in __call__
origin-container |     return TaskBase.__call__(self, *args, **kwargs)
origin-container |   File "/opt/bridge-server/bridge-server-venv/lib/python3.6/site-packages/celery/app/trace.py", line 629, in __protected_call__
origin-container |     return self.run(*args, **kwargs)
origin-container |   File "/opt/bridge-server/source/util/tasks.py", line 69, in event_listener
origin-container |     transaction_index=event_tracker.transaction_index)
origin-container |   File "/opt/bridge-server/source/util/contract.py", line 63, in fetch_events
origin-container |     callback(event)
origin-container |   File "/opt/bridge-server/source/logic/indexer_service.py", line 234, in process
origin-container |     purchase_obj = self.db_indexer.create_or_update_purchase(data)
origin-container |   File "/opt/bridge-server/source/logic/indexer_service.py", line 81, in create_or_update_purchase
origin-container |     db.session.commit()
origin-container |   File "/opt/bridge-server/bridge-server-venv/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 153, in do
origin-container |     return getattr(self.registry(), name)(*args, **kwargs)
origin-container |   File "/opt/bridge-server/bridge-server-venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 943, in commit
origin-container |     self.transaction.commit()
origin-container |   File "/opt/bridge-server/bridge-server-venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 467, in commit
origin-container |     self._prepare_impl()
origin-container |   File "/opt/bridge-server/bridge-server-venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
origin-container |     self.session.flush()
origin-container |   File "/opt/bridge-server/bridge-server-venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2254, in flush
origin-container |     self._flush(objects)
origin-container |   File "/opt/bridge-server/bridge-server-venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2380, in _flush
origin-container |     transaction.rollback(_capture_exception=True)
origin-container |   File "/opt/bridge-server/bridge-server-venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
origin-container |     compat.reraise(exc_type, exc_value, exc_tb)
origin-container |   File "/opt/bridge-server/bridge-server-venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
origin-container |     raise value
origin-container |   File "/opt/bridge-server/bridge-server-venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2344, in _flush
origin-container |     flush_context.execute()
origin-container |   File "/opt/bridge-server/bridge-server-venv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 391, in execute
origin-container |     rec.execute(self)
origin-container |   File "/opt/bridge-server/bridge-server-venv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 556, in execute
origin-container |     uow
origin-container |   File "/opt/bridge-server/bridge-server-venv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
origin-container |     mapper, table, insert)
origin-container |   File "/opt/bridge-server/bridge-server-venv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 830, in _emit_insert_statements
origin-container |     execute(statement, multiparams)
origin-container |   File "/opt/bridge-server/bridge-server-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
origin-container |     return meth(self, multiparams, params)
origin-container |   File "/opt/bridge-server/bridge-server-venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
origin-container |     return connection._execute_clauseelement(self, multiparams, params)
origin-container |   File "/opt/bridge-server/bridge-server-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
origin-container |     compiled_sql, distilled_params
origin-container |   File "/opt/bridge-server/bridge-server-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
origin-container |     context)
origin-container |   File "/opt/bridge-server/bridge-server-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
origin-container |     exc_info
origin-container |   File "/opt/bridge-server/bridge-server-venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
origin-container |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
origin-container |   File "/opt/bridge-server/bridge-server-venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
origin-container |     raise value.with_traceback(tb)
origin-container |   File "/opt/bridge-server/bridge-server-venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
origin-container |     context)
origin-container |   File "/opt/bridge-server/bridge-server-venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
origin-container |     cursor.execute(statement, parameters)
origin-container | sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) insert or update on table "purchase" violates foreign key constraint "purchase_listing_address_fkey"
origin-container | DETAIL:  Key (listing_address)=(0x4E205e04A1A8f230702fe51f3AfdCC38aafB0f3C) is not present in table "listing".
origin-container |  [SQL: 'INSERT INTO purchase (contract_address, buyer_address, listing_address, stage, created_at, buyer_timeout) VALUES (%(contract_address)s, %(buyer_address)s, %(listing_address)s, %(stage)s, %(created_at)s, %(buyer_timeout)s)'] [parameters: {'contract_address': '0xCa163A64f8c3d8A6c15A46f95DA492476Ef3E613', 'buyer_address': '0xC5fdf4076b8F3A5357c5E395ab970B5B54098Fef', 'listing_address': '0x4E205e04A1A8f230702fe51f3AfdCC38aafB0f3C', 'stage': 1, 'created_at': datetime.datetime(2018, 6, 17, 3, 59), 'buyer_timeout': datetime.datetime(1970, 1, 1, 0, 0)}] (Background on this error at: http://sqlalche.me/e/gkpj)
```

`listing` and `purchase` tables inside docker in postgres are empty.

**Comment by sparrowDom** [comment]
The referenced pull request solved the issue for me.
